variable "vpc-name" {}
variable "igw-name" {}
variable "rt-name" {}
variable "subnet-name" {}
variable "sg-name" {}
variable "instance_name" {}
variable "key_name" {}
variable "iam_role" {}
variable "region" {}
variable "volume_size" {}
variable "instance_type" {}
